name: Restart Server

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restart Server
        run: |
          echo "Restarting server..."
          #we will add restart command here